dist: xenial
language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8 

script:
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake ..
  - cmake --build .
  - test/FuelGaugeTest

